-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.3
    hooks:
    -   id: trailing-whitespace
        args: ['--no-markdown-linebreak-ext']
    -   id: check-yaml
    -   id: end-of-file-fixer
